"""message

Revision ID: 0421b3616322
Revises: d869e8d143d5
Create Date: 2024-07-07 23:41:52.913496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0421b3616322'
down_revision = 'd869e8d143d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
